name: Deploy to EC2

on:
  push:
    branches: [ main ]

env:
    AWS_REGION: eu-west-1
    CONTAINER_NAME: coffee-wifi
    ECR_REGISTRY: 430118857028.dkr.ecr.eu-west-1.amazonaws.com
    ECR_REPOSITORY: coffee-wifi
    IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    #Step 1: Checkout the code
    - name: Check out code
      uses: actions/checkout@v2
    
    #Step 2: Log in to AWS CLI
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.USER }}
        aws-secret-access-key: ${{ secrets.SSH_KEY }}
        aws-region: eu-west-1

    #Step 3: Login to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Debugging Environment
      run: |
        echo "AWS_REGION: $AWS_REGION"
        echo "ECR_REGISTRY: $ECR_REGISTRY"
        echo "ECR_REPOSITORY: $ECR_REPOSITORY"
        echo "IMAGE_TAG: $IMAGE_TAG"
        echo "CONTAINER_NAME: $CONTAINER_NAME"