name: Deploy to ECR

on:
  push:
    branches: [ main ]


jobs:
  build:
    
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.USER }}
        aws-secret-access-key: ${{ secrets.SSH_KEY }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
        ECR_REPOSITORY: coffee-wifi
        IMAGE_TAG: Latest
      run: |
        docker build -t 430118857028.dkr.ecr.eu-west-1.amazonaws.com:Latest .
        docker tag coffee-wifi:Latest 430118857028.dkr.ecr.eu-west-1.amazonaws.com/coffee-wifi:Latest
        docker push 430118857028.dkr.ecr.eu-west-1.amazonaws.com/coffee-wifi:Latest
